---
- hosts: all
  name: Digital Ocean Server Setup
  become: yes

  vars_files:
    - ./devenv_vars.default.yml
    - ./devenv_vars.config.yml

  vars:
    # TODO: figure out dynamic mount points
    block_storage_mount_root: /data
    root_my_cnf_path: ~root/.my.cnf
    block_storage_device: /dev/sda
    block_storage_format: xfs

  tasks:

    - name: Check for block storage device
      stat:
        path: "{{ block_storage_device }}"
      register: block_storage_device_stat

    - name: "Mount attached block storage (if applicable)"
      block:

      - debug:
          verbosity: 1
          msg: "Detected block storage at {{ block_storage_device }}"

      - name: Partition attached block storage
        parted:
          device: "{{ block_storage_device }}"
          number: 1
          state: present
      - name: Format attached block storage
        filesystem:
          fstype: "{{ block_storage_format }}"
          dev: "{{ block_storage_device }}"
      - name: Mount attached block storage
        mount:
          path: "{{ block_storage_mount_root }}"
          src: "{{ block_storage_device }}"
          fstype: "{{ block_storage_format }}"
          opts: discard,defaults,noatime
          state: mounted

      - name: Create mysql bind data directory
        file:
          path: "{{ block_storage_mount_root }}/mysql"
          state: directory
      - name: Bind mount mysql data directory
        mount:
          path: "{{ mysqld_datadir }}"
          src: "{{ block_storage_mount_root }}/mysql"
          opts: bind
          state: mounted
          fstype: none

      - name: Create block storage shared dir
        file:
          path: "{{ block_storage_mount_root }}/.shared"
          state: directory

      - name: Check for block storage shared root my.cnf
        stat:
          path: "{{ block_storage_mount_root }}/.shared/root-my.cnf"
        register: shared_root_my_cnf_file

      - name: Copy shared root my.cnf into local machine (if applicable)
        copy:
          remote_src: yes
          src: "{{ block_storage_mount_root }}/.shared/root-my.cnf"
          dest: "{{ root_my_cnf_path }}"
        when: shared_root_my_cnf_file.stat.exists 

      when: block_storage_device_stat.stat.exists
